# -*- coding: utf-8 -*-
"""CreditDecisioningAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHfVI1IAgrHdkN1SJZCJ56OP9X-36p6P
"""

"""
© 2026 Aethryx Pte. Ltd.

Reference implementation for AI Governance Control Plane.
For demonstration purposes only.

End-to-End Reference Implementation
Use Case: Agentic Credit Decisioning System

This script shows a simplified runtime governance implementation for:
1. Assess & bound risks upfront
2. Make humans meaningfully accountable
3. Implement technical controls & processes
4. Enable end-user responsibility
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any
import time
import uuid


# =========================================================
# DIMENSION 1: ASSESS & BOUND RISKS UPFRONT
# =========================================================

@dataclass
class AgentConfig:
    agent_id: str
    name: str
    allowed_tools: List[str]
    write_permissions: bool = False
    autonomy_level: str = "LOW"
    max_transaction_amount: float = 0.0
    owner: str = "Head of Credit AI"
    environment: str = "PRODUCTION"


def classify_risk(use_case: str) -> str:
    """Basic use-case classification."""
    high_risk_cases = {
        "credit_decision",
        "loan_approval",
        "fraud_investigation",
        "payment_authorization"
    }
    return "HIGH" if use_case in high_risk_cases else "LOW"


def check_tool_access(agent: AgentConfig, tool: str) -> bool:
    """Enforce tool restrictions."""
    return tool in agent.allowed_tools


def enforce_read_only(agent: AgentConfig) -> bool:
    """Agent is bounded to read-only where needed."""
    return not agent.write_permissions


def validate_transaction_limit(agent: AgentConfig, amount: float) -> bool:
    """Ensure the agent cannot execute beyond its delegated scope."""
    return amount <= agent.max_transaction_amount


# =========================================================
# DIMENSION 2: MAKE HUMANS MEANINGFULLY ACCOUNTABLE
# =========================================================

ACCOUNTABILITY = {
    "agent_owner": "Head of Credit AI",
    "approver": "Credit Officer",
    "audit": "Risk Team",
    "model_risk_owner": "Model Risk Management",
    "compliance_owner": "Compliance Officer"
}


def requires_approval(risk_score: str, loan_amount: float) -> bool:
    """Approval logic for high-risk or high-value decisions."""
    return risk_score == "HIGH" or loan_amount > 10000


def route_to_human(role: str, decision_context: Dict[str, Any]) -> str:
    """Simulate human approval routing."""
    print(f"[HUMAN REVIEW] Routed to {role}: {decision_context}")
    return "PENDING_HUMAN_APPROVAL"


def process_decision(agent_output: Dict[str, Any]) -> str:
    """Route agent output to auto-approve or human review."""
    if requires_approval(agent_output["risk"], agent_output["amount"]):
        return route_to_human("Credit Officer", agent_output)
    return "AUTO_APPROVED"


# =========================================================
# DIMENSION 3: IMPLEMENT TECHNICAL CONTROLS & PROCESSES
# =========================================================

def compute_runtime_risk(base_risk: float, anomaly_score: float, dependency_risk: float) -> float:
    """
    Dynamic risk tiering:
    runtime risk = base + anomaly contribution + dependency contribution
    """
    return base_risk + anomaly_score + (0.5 * dependency_risk)


def enforce_guardrails(risk_score: float) -> str:
    """
    Guardrail policy:
    > 5   => restrict agent
    > 3   => limit actions
    else  => allow
    """
    if risk_score > 5:
        return "RESTRICT_AGENT"
    elif risk_score > 3:
        return "LIMIT_ACTIONS"
    return "ALLOW"


def trigger_alert(alert_type: str, details: Dict[str, Any] | None = None) -> None:
    """Alerting hook."""
    print(f"[ALERT] {alert_type} | details={details}")


def monitor_agent(activity: Dict[str, Any]) -> None:
    """Runtime monitoring."""
    if activity.get("anomaly", False):
        trigger_alert("ANOMALY_DETECTED", activity)


def detect_drift(current_output: float, baseline: float, threshold: float = 0.2) -> bool:
    """Simple drift detection."""
    return abs(current_output - baseline) > threshold


def apply_runtime_controls(guardrail_action: str, agent: AgentConfig) -> None:
    """Enforce runtime constraints."""
    if guardrail_action == "RESTRICT_AGENT":
        print(f"[CONTROL] Agent {agent.name} restricted. Escalating to human.")
    elif guardrail_action == "LIMIT_ACTIONS":
        print(f"[CONTROL] Agent {agent.name} action-space reduced.")
    else:
        print(f"[CONTROL] Agent {agent.name} allowed to continue.")


# =========================================================
# DIMENSION 4: ENABLE END-USER RESPONSIBILITY
# =========================================================

def build_decision_trace(
    input_data: str,
    steps: List[str],
    tools_used: List[str],
    risk_score: float,
    final_action: str
) -> Dict[str, Any]:
    """Decision traceability record."""
    return {
        "trace_id": str(uuid.uuid4()),
        "input": input_data,
        "steps": steps,
        "tools_used": tools_used,
        "risk_score": risk_score,
        "final_action": final_action,
        "timestamp": time.time()
    }


def explain_decision(trace: Dict[str, Any]) -> str:
    """Human-readable explanation."""
    return (
        f"Decision trace {trace['trace_id']}: "
        f"risk score={trace['risk_score']}, "
        f"tools used={trace['tools_used']}, "
        f"final action={trace['final_action']}."
    )


def notify_user() -> str:
    """User-facing transparency message."""
    return "This decision was AI-assisted and requires human validation where applicable."


# =========================================================
# SUPPORTING LOGIC
# =========================================================

def fetch_customer_data(customer_id: str) -> Dict[str, Any]:
    """Simulated data retrieval."""
    return {
        "customer_id": customer_id,
        "income": 120000,
        "existing_debt": 15000,
        "credit_score": 720,
        "requested_loan_amount": 25000
    }


def score_credit_risk(customer_data: Dict[str, Any]) -> float:
    """
    Simplified risk scoring.
    Lower is better in this toy example.
    """
    credit_score = customer_data["credit_score"]
    debt_ratio = customer_data["existing_debt"] / max(customer_data["income"], 1)

    # crude illustrative score
    risk = 0.0
    if credit_score < 650:
        risk += 2.5
    elif credit_score < 700:
        risk += 1.5
    else:
        risk += 0.5

    if debt_ratio > 0.4:
        risk += 2.5
    elif debt_ratio > 0.2:
        risk += 1.0
    else:
        risk += 0.3

    return round(risk, 2)


def recommend_credit_decision(customer_data: Dict[str, Any], runtime_risk: float) -> str:
    """Agent recommendation."""
    if runtime_risk > 5:
        return "DECLINE"
    elif runtime_risk > 3:
        return "REVIEW"
    return "APPROVE"


# =========================================================
# RUNTIME GOVERNANCE LAYER
# =========================================================

class GovernanceEngine:
    def __init__(self, agent: AgentConfig):
        self.agent = agent
        self.agent_is_running = True
        self.baseline_output = 2.0

    def run_credit_decision_workflow(self, customer_id: str, use_case: str = "credit_decision") -> Dict[str, Any]:
        # 1. Upfront risk classification
        risk_label = classify_risk(use_case)
        print(f"[INFO] Use case risk classification: {risk_label}")

        # 2. Tool access checks
        required_tools = ["read_customer_data", "credit_score_api"]
        for tool in required_tools:
            if not check_tool_access(self.agent, tool):
                raise PermissionError(f"Agent cannot access tool: {tool}")

        # 3. Read-only / bounded action checks
        if not enforce_read_only(self.agent):
            raise PermissionError("Agent must be read-only for this workflow.")

        # 4. Retrieve data
        customer_data = fetch_customer_data(customer_id)

        # 5. Agent performs scoring
        base_risk = score_credit_risk(customer_data)

        # 6. Simulated anomaly / dependency risk signals
        anomaly_score = 1.2 if customer_data["requested_loan_amount"] > 20000 else 0.2
        dependency_risk = 1.5  # Example upstream system / model dependency contribution

        runtime_risk = compute_runtime_risk(base_risk, anomaly_score, dependency_risk)
        print(f"[INFO] Runtime risk score: {runtime_risk}")

        # 7. Monitoring
        activity = {
            "customer_id": customer_id,
            "anomaly": anomaly_score > 1.0,
            "runtime_risk": runtime_risk
        }
        monitor_agent(activity)

        # 8. Drift detection
        drift_detected = detect_drift(runtime_risk, self.baseline_output, threshold=1.0)
        if drift_detected:
            trigger_alert(
                "DRIFT_DETECTED",
                {"current_output": runtime_risk, "baseline": self.baseline_output}
            )

        # 9. Runtime guardrails
        guardrail_action = enforce_guardrails(runtime_risk)
        apply_runtime_controls(guardrail_action, self.agent)

        # 10. Recommendation
        recommendation = recommend_credit_decision(customer_data, runtime_risk)

        # 11. Human accountability checkpoint
        decision_context = {
            "customer_id": customer_id,
            "risk": risk_label,
            "runtime_risk": runtime_risk,
            "amount": customer_data["requested_loan_amount"],
            "recommendation": recommendation
        }

        approval_status = process_decision(decision_context)

        # 12. Decision trace
        trace = build_decision_trace(
            input_data=f"Customer {customer_id} profile",
            steps=[
                "fetch customer data",
                "calculate base risk",
                "calculate runtime risk",
                "apply guardrails",
                "recommend decision",
                "route for approval if required"
            ],
            tools_used=required_tools,
            risk_score=runtime_risk,
            final_action=approval_status
        )

        # 13. User-facing explanation
        explanation = explain_decision(trace)
        user_notice = notify_user()

        result = {
            "customer_data": customer_data,
            "risk_label": risk_label,
            "runtime_risk": runtime_risk,
            "guardrail_action": guardrail_action,
            "recommendation": recommendation,
            "approval_status": approval_status,
            "decision_trace": trace,
            "explanation": explanation,
            "user_notice": user_notice
        }

        return result

    def continuous_runtime_loop(self, cycles: int = 3) -> None:
        """
        Demonstrates the think-piece angle:
        continuous governance, not static governance.
        """
        threshold = 4.0

        for i in range(cycles):
            if not self.agent_is_running:
                break

            simulated_base_risk = 2.0 + i * 0.5
            simulated_anomaly = 0.5 if i < 2 else 1.8
            simulated_dependency = 1.0

            risk = compute_runtime_risk(
                simulated_base_risk,
                simulated_anomaly,
                simulated_dependency
            )

            print(f"[LOOP] Cycle={i+1}, runtime risk={risk}")

            if risk > threshold:
                action = enforce_guardrails(risk)
                apply_runtime_controls(action, self.agent)
                trigger_alert("THRESHOLD_BREACH", {"cycle": i + 1, "risk": risk})
                route_to_human("Credit Officer", {"cycle": i + 1, "risk": risk})

            time.sleep(0.5)


# =========================================================
# MAIN
# =========================================================

def main() -> None:
    agent = AgentConfig(
        agent_id="agent-credit-001",
        name="Credit Decision Agent",
        allowed_tools=["read_customer_data", "credit_score_api"],
        write_permissions=False,
        autonomy_level="LOW",
        max_transaction_amount=0.0,
        owner="Head of Credit AI"
    )

    engine = GovernanceEngine(agent)

    print("\n=== RUNNING CREDIT DECISION WORKFLOW ===")
    result = engine.run_credit_decision_workflow(customer_id="CUST-1001")

    print("\n=== FINAL RESULT ===")
    for key, value in result.items():
        print(f"{key}: {value}")

    print("\n=== CONTINUOUS RUNTIME GOVERNANCE LOOP ===")
    engine.continuous_runtime_loop(cycles=3)


if __name__ == "__main__":
    main()

